# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8c67c86cec1c24fe9ca74ea3f4fda8c25340890cc3a580a898b87ba05e140879f051700635621a3e297ff30b843fb71b3cd52c3fcf10b7a1c0173ff7bdfb050

test:
  secret_key_base: 02f1aa880faffd1bc94618505de2ab35ca2aba0a2800530a315af86d030749171054139bc162b77b231256df413b44eb01aee322f1e3e544fe4f5c56d57d3f2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
